stages:
    - build
    - deploy

build_dgx:
    image: gccdockers/annotat3d:cuda-11.2
    stage: build
    script:
        - python3 setup.py bdist_wheel --cuda
    tags:
        - x86_64
        - cuda11
    artifacts:
        paths:
            - ./dist/*whl
        expire_in: 1 day

build_power:
    stage: build
    script:
        - python3 setup.py bdist_wheel --cuda
    tags:
        - ppc64le
        - cuda10
    artifacts:
        paths:
            - ./dist/*whl
        expire_in: 1 day

deploy_dgx:
    stage: deploy
    image: gccdockers/annotat3d:cuda-11.2
    script:
        - python3 -m pip install keyring==12.0.0 keyrings.alt
        - python3 -m pip install twine==2.0.0 passlib
        - twine upload ./dist/*.whl  --repository-url="$GCC_PYPI_HOST"
    tags:
        - x86_64
        - cuda11
    dependencies:
        - build_dgx
    only:
        - tags

deploy_power:
    stage: deploy
    script:
        - python3 -m pip install keyring==12.0.0 keyrings.alt
        - python3 -m pip install twine==2.0.0 passlib
        - python3 -m twine upload ./dist/*.whl --repository-url="$GCC_PYPI_HOST"
    tags:
        - ppc64le
        - cuda10
    dependencies:
        - build_power
    only:
        - tags
