variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --remote

stages:
    - build
    - deploy

build_dgx:
    stage: build
    image: gccdockers/python-builder
    script:
        - python3 -m build --wheel
    tags:
        - x86_64
        - cuda11
        - docker
    artifacts:
        paths:
            - ./dist/*whl
        expire_in: 1 day

deploy_dgx:
    stage: deploy
    image: gccdockers/python-builder
    script:
        - python3 -m twine upload ./dist/*.whl  --repository-url="$GCC_PYPI_HOST"
    tags:
        - x86_64
        - cuda11
        - docker
    dependencies:
        - build_dgx
    only:
        - tags

build_docs:
  image: gccdockers/python-builder
  stage: build
  script:
    - cd docs
    - make all
  tags:
    - x86_64
    - docker
  artifacts:
    paths:
      - ./docs/build/
    expire_in: 1 day

deploy_docs:
  stage: deploy
  image: ubuntu:latest
  script:
    - mkdir -p /var/www/html/ssc/ssc-cdi/
    - rm -rf /var/www/html/ssc/ssc-cdi/*
    - cp -r ./docs/build/html/* /var/www/html/ssc/ssc-cdi/
  tags:
    - wiki
  only:
    - tags
